on:
  push:
    tags:
      - 'v*'
name: Builds and pushes tagged image to ECR and DockerHub
jobs:
  build_push_ecr:
    name: Push image to ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{secrets.AWS_PROD_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com
          username: ${{ secrets.ECR_ACCESS_ID }}
          password: ${{ secrets.ECR_ACCESS_KEY }}
      - name: Find Git Tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{secrets.AWS_PROD_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com/gh-runner:latest
            ${{secrets.AWS_PROD_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com/gh-runner:${{ env.TAG }}
  build_push_docker_hub:
    name: Push image Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Find Git Tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            passeidireto/gh-runner:latest
            passeidireto/gh-runner:${{ env.TAG }}
  trigger-test-workflow:
    name: Triggers simple test workflow to ensure everything still working as expected
    runs-on: ubuntu-latest
    steps:
      - uses: passeidireto/trigger-external-workflow-action@main
        if: success()
        with:
          repository: PasseiDireto/gh-runner
          event: successful_release
          github_pat: ${{ secrets.PD_BOT_GITHUB_ACCESS_TOKEN }}
